/**
 * Generates the Phase C seed migration from VERIFIED_PRODUCTS.
 *
 * Run whenever the bundled verified catalog changes:
 *   npx tsx scripts/generate-catalog-seed.ts
 *
 * The migration is idempotent (INSERT ... ON CONFLICT (id) DO NOTHING),
 * preserves product IDs (the key used by PRODUCT_IMAGE_MAP and
 * validateProductImage), and never overwrites cloud rows that the
 * shop owner has already edited.
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { VERIFIED_PRODUCTS } from '../src/data/verifiedProducts';

const OUT = join(import.meta.dirname, '..', 'supabase', 'migrations', '20260919141000_phase_c_seed_verified_catalog.sql');

const esc = (v: string) => v.replace(/'/g, "''");
const q = (v: string | null | undefined) => (v === null || v === undefined ? 'NULL' : `'${esc(v)}'`);
const num = (v: number | null | undefined) => (v === null || v === undefined ? 'NULL' : String(v));
const bool = (v: boolean | null | undefined) => (v ? 'TRUE' : 'FALSE');
const jsonb = (v: unknown) => `'${esc(JSON.stringify(v ?? []))}'::jsonb`;

const COLUMNS = `id, name, slug, description, price, mrp, discount_percent, category_id, category_name,
  image_url, additional_images, in_stock, featured, is_active, archived_at, source, reference_verified,
  is_mystery_scoop, is_kashmiri_earring, tags, created_at, updated_at`;

const rows = VERIFIED_PRODUCTS.map((p) => `(
    ${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${num(p.price)}, ${num(p.mrp)},
    ${num(p.discount_percent)}, ${q(p.category_id)}, ${q(p.category_name ?? null)}, ${q(p.image_url)},
    ${jsonb(p.additional_images)}, ${bool(p.in_stock)}, ${bool(p.featured)}, TRUE, NULL,
    ${q(p.source ?? null)}, ${bool(p.reference_verified)}, ${bool(p.is_mystery_scoop)},
    ${bool(p.is_kashmiri_earring)}, ${jsonb(p.tags)}, ${q(p.created_at ?? null)}, ${q(p.updated_at ?? null)}
  )`);

const sql = `-- ==========================================================
-- CHARMS HUB AI — PHASE C: SEED VERIFIED CATALOG
-- AUTO-GENERATED by scripts/generate-catalog-seed.ts — DO NOT EDIT.
-- Source of truth: src/data/verifiedProducts.ts (${VERIFIED_PRODUCTS.length} products)
--
-- Seeds the authoritative cloud catalog while preserving product IDs
-- (PRODUCT_IMAGE_MAP / validateProductImage key on product.id).
-- Idempotent: never overwrites rows an owner has already edited.
-- ==========================================================

INSERT INTO public.products (${COLUMNS})
VALUES
${rows.join(',\n')}
ON CONFLICT (id) DO NOTHING;
`;

writeFileSync(OUT, sql);
console.log(`Wrote ${OUT} with ${rows.length} product rows.`);
