-- ==========================================================
-- CHARMS HUB AI — PHASE C: SEED VERIFIED CATALOG
-- AUTO-GENERATED by scripts/generate-catalog-seed.ts — DO NOT EDIT.
-- Source of truth: src/data/verifiedProducts.ts (42 products)
--
-- Seeds the authoritative cloud catalog while preserving product IDs
-- (PRODUCT_IMAGE_MAP / validateProductImage key on product.id).
-- Idempotent: never overwrites rows an owner has already edited.
-- ==========================================================

INSERT INTO public.products (id, name, slug, description, price, mrp, discount_percent, category_id, category_name,
  image_url, additional_images, in_stock, featured, is_active, archived_at, source, reference_verified,
  is_mystery_scoop, is_kashmiri_earring, tags, created_at, updated_at)
VALUES
(
    'prod-pookia-mystery-scoop', 'Pookia Mystery scoop', 'pookia-mystery-scoop', 'Our signature Pookia Mystery Scoop packed with aesthetic mini charms, hair accessories, cute rings, and surprise accessories curated by Charms Hub.', 399, 499,
    20, 'cat-mystery-scoop', 'Mystery Scoop', '/products/mystery-scoop/pookia-mystery-scoop.webp',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, TRUE,
    FALSE, '["mystery","scoop","pookia","bestseller","surprise"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-mini-mystery-scoop', 'Mini mystery scoop', 'mini-mystery-scoop', 'A pocket-friendly mini mystery scoop with cute jewelry items and hair accessories packed with love.', 399, 499,
    20, 'cat-mystery-scoop', 'Mystery Scoop', '/products/mystery-scoop/mini-mystery-scoop.webp',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, TRUE,
    FALSE, '["mystery","scoop","mini","budget"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-anti-tarnish-mystery-scoop', 'Anti-tarnish Jewelry Mystery scoop', 'anti-tarnish-jewelry-mystery-scoop', 'Curated scoop filled only with premium anti-tarnish stainless steel gold and silver jewelry designed for daily wear.', 799, 999,
    20, 'cat-mystery-scoop', 'Mystery Scoop', '/products/mystery-scoop/anti-tarnish-jewelry-mystery-scoop.webp',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, TRUE,
    FALSE, '["mystery","anti-tarnish","jewelry","scoop","gold"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-luxury-mystery-scoop', 'Luxury Mystery scoop', 'luxury-mystery-scoop', 'Our most lavish scoop featuring premium anti-tarnish bracelets, luxury lockets, Korean bows, and organizer cases.', 1200, 1500,
    20, 'cat-mystery-scoop', 'Mystery Scoop', '/products/mystery-scoop/luxury-mystery-scoop.jpg',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, TRUE,
    FALSE, '["luxury","mystery","gift","premium"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-7', 'Kashmiri Earring - Design 7', 'kashmiri-earring-design-7', 'Traditional handcrafted Kashmiri chandelier earrings with intricate metal carving and pearl drops.', 499, 599,
    17, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-7.webp',
    '[]'::jsonb, FALSE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","traditional","jhumka"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-6', 'Kashmiri Earring - Design 6', 'kashmiri-earring-design-6', 'Statement Kashmiri ethnic earrings with regal silhouette and fine bead tassel accents.', 499, 599,
    17, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-6.webp',
    '[]'::jsonb, FALSE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","ethnic"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-5', 'Kashmiri Earring - Design 5', 'kashmiri-earring-design-5', 'Gold-finish Kashmiri jhumka earrings featuring floral studs and delicate jhumki drops.', 349, 399,
    13, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-5.jpg',
    '["/products/earrings/kashmiri-earring-design-5-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","jhumka"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-4', 'Kashmiri Earring - Design 4', 'kashmiri-earring-design-4', 'Intricate filigree Kashmiri dangle earrings crafted with antique gold and pearl accents.', 349, 399,
    13, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-4.jpg',
    '["/products/earrings/kashmiri-earring-design-4-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","filigree"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-3', 'Kashmiri Earring - Design 3', 'kashmiri-earring-design-3', 'Ornate Kashmiri heritage earrings with cascading pearls and mirror stone embellishments.', 499, 599,
    17, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-3.jpg',
    '["/products/earrings/kashmiri-earring-design-3-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","statement"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-2', 'Kashmiri Earring - Design 2', 'kashmiri-earring-design-2', 'Classic Kashmiri bell jhumkas with fine floral motifs and lightweight comfortable clasp.', 399, 499,
    20, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-2.jpg',
    '["/products/earrings/kashmiri-earring-design-2-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","bestseller"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-kashmiri-earring-1', 'Kashmiri Earring - Design 1', 'kashmiri-earring-design-1', 'Opulent Kashmiri grand earrings worn by brides and for festivities, rich gold plating.', 499, 599,
    17, 'cat-earrings', 'Earrings', '/products/earrings/kashmiri-earring-design-1.jpg',
    '["/products/earrings/kashmiri-earring-design-1-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    TRUE, '["earrings","kashmiri","festive"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-solar-daisy-charm-bangle', 'The Solar Daisy Charm Bangle', 'the-solar-daisy-charm-bangle', 'Delicate gold-toned bangle featuring a luminous daisy charm with enamel petals and anti-tarnish finish.', 350, 399,
    12, 'cat-bracelets', 'Bracelets', '/products/bracelets/the-solar-daisy-charm-bangle.webp',
    '[]'::jsonb, FALSE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bangle","daisy","bracelet","floral","anti-tarnish"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-triple-row-geometric-bangle', 'The Triple-Row Geometric Lattice Bangle', 'the-triple-row-geometric-lattice-bangle', 'A striking triple-row structured lattice bangle in glistening gold tone, perfect for festive and casual chic.', 350, 399,
    12, 'cat-bracelets', 'Bracelets', '/products/bracelets/the-triple-row-geometric-lattice-bangle.webp',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bangle","lattice","geometric","gold","bracelet"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-the-silver-wave-bracelet', 'The Silver Wave Bracelet', 'the-silver-wave-bracelet', 'Polished rhodium finish fluid wave pattern bracelet with secure clasp.', 200, 250,
    20, 'cat-bracelets', 'Bracelets', '/products/bracelets/the-silver-wave-bracelet.jpg',
    '["/products/bracelets/the-silver-wave-bracelet-1.jpg","/products/bracelets/the-silver-wave-bracelet-2.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","silver","wave"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-the-greek-key-bracelet', 'The Greek Key Bracelet', 'the-greek-key-bracelet', 'Timeless Roman/Greek key motif engraved luxury cuff bracelet in lustrous rose gold finish.', 200, 250,
    20, 'cat-bracelets', 'Bracelets', '/products/bracelets/the-greek-key-bracelet.jpg',
    '["/products/bracelets/the-greek-key-bracelet-1.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","greek key","cuff","rose gold"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-gucci-bracelet', 'GUCCI Bracelet', 'gucci-bracelet', 'Aesthetic interlocking link statement bracelet with premium glossy metallic plating.', 200, 250,
    20, 'cat-bracelets', 'Bracelets', '/products/bracelets/gucci-bracelet.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","designer","chain"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-love-heartbeat-bracelet', 'Love heartbeat Bracelet', 'love-heartbeat-bracelet', 'Dainty chain bracelet with an electrocardiogram heartbeat pulse charm and tiny red heart stone.', 170, 210,
    19, 'cat-bracelets', 'Bracelets', '/products/bracelets/love-heartbeat-bracelet.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","heartbeat","heart","dainty"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-infinity-bracelet', 'Infinity Bracelet', 'infinity-bracelet', 'Elegant symbol of forever with cubic zirconia studded infinity loop on slender gold chain.', 170, 210,
    19, 'cat-bracelets', 'Bracelets', '/products/bracelets/infinity-bracelet.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","infinity","charm"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-princess-crown-bracelet', 'Princess Crown Bracelet', 'princess-crown-bracelet', 'Royal mini tiara charm centered on an adjustable link chain.', 170, 210,
    19, 'cat-bracelets', 'Bracelets', '/products/bracelets/princess-crown-bracelet.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["bracelet","princess","crown"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-travelling-makeup-organizer', 'Travelling Makeup Organizer', 'travelling-makeup-organizer', 'Compact travel cosmetic case with multiple zippered compartments, brush loops, and wipe-clean lining.', 499, 699,
    29, 'cat-organizers', 'Organizers', '/products/organizers/travelling-makeup-organizer.jpg',
    '["/products/organizers/travelling-makeup-organizer-1.jpg","/products/organizers/travelling-makeup-organizer-2.jpg","/products/organizers/travelling-makeup-organizer-3.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["organizer","travel","makeup","pouch"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-5-in-1-rose-ring-box', '5 in 1 Rose Ring Gift Box', '5-in-1-rose-ring-gift-box', 'Stunning velvet rose flower presentation gift box holding 5 interchangeable romantic rings.', 450, 599,
    25, 'cat-unique-products', 'Unique Products', '/products/organizers/5-in-1-rose-ring-gift-box.jpg',
    '["/products/organizers/5-in-1-rose-ring-gift-box-1.jpg","/products/organizers/5-in-1-rose-ring-gift-box-2.jpg","/products/organizers/5-in-1-rose-ring-gift-box-3.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["gift","rose","rings","box","unique"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-square-rose-gift-box', 'Square Rose Gift Box with Jewelry', 'square-rose-gift-box-with-jewelry', 'Luxury preserved crimson rose showcase box with slide-out drawer containing heart crystal pendant.', 1000, 1500,
    33, 'cat-unique-products', 'Unique Products', '/products/organizers/square-rose-gift-box-with-jewelry.webp',
    '["/products/organizers/square-rose-gift-box-with-jewelry-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["gift","rose","jewelry box","luxury"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-round-rose-rotating-box', 'Round Rose Rotating Jewelry box with Locket', 'round-rose-rotating-jewelry-box-with-locket', 'Interactive rotating mechanical flower presentation case that reveals a hidden locket.', 1200, 1500,
    20, 'cat-unique-products', 'Unique Products', '/products/organizers/round-rose-rotating-jewelry-box-with-locket.jpg',
    '["/products/organizers/round-rose-rotating-jewelry-box-with-locket-1.jpg","/products/organizers/round-rose-rotating-jewelry-box-with-locket-2.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["gift box","rotating","locket","rose"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-jewelry-book', 'Jewelry Book', 'jewelry-book', 'Vintage storybook style jewelry organizer with felt pages for earrings, rings, and chains.', 599, 799,
    25, 'cat-organizers', 'Organizers', '/products/organizers/jewelry-book.jpg',
    '["/products/organizers/jewelry-book-1.jpg","/products/organizers/jewelry-book-2.jpg","/products/organizers/jewelry-book-3.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["organizer","jewelry book","travel"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-3d-pouch-organizer', '3D Pouch Jewelry Organizer', '3d-pouch-jewelry-organizer', 'Spacious 3D expandable travel pouch with organized anti-tarnish compartments.', 450, 599,
    25, 'cat-organizers', 'Organizers', '/products/organizers/3d-pouch-jewelry-organizer.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["organizer","pouch","travel"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-glue-pen', 'Glue Pen', 'glue-pen', 'Precision fine-point dispensable adhesive glue pen for journaling, crafts, and scrapbooking.', 70, 100,
    30, 'cat-quirky-stationery', 'Quirky Stationery', '/products/stationery/glue-pen.jpg',
    '["/products/stationery/glue-pen-1.jpg","/products/stationery/glue-pen-2.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["stationery","craft","glue pen"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-numbing-cream-earrings', 'Numbing cream for Earrings', 'numbing-cream-for-earrings', 'Gentle topical cream to ease piercing sensitivity and comfort while wearing heavy statement jhumkas.', 75, NULL,
    NULL, 'cat-unique-products', 'Unique Products', '/products/organizers/numbing-cream-for-earrings.jpg',
    '[]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["earrings","care","numbing cream","accessory"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-pokemon-sharpener', 'Pokémon sharpener', 'pokemon-sharpener', 'Collectible miniature Pikachu / Pokémon pencil sharpener with shavings reservoir.', 140, 199,
    30, 'cat-quirky-stationery', 'Quirky Stationery', '/products/stationery/pokemon-sharpener.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["stationery","pokemon","sharpener","quirky"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-mickey-mouse-sharpeners', 'Mickey Mouse sharpeners', 'mickey-mouse-sharpeners', 'Adorably styled Mickey Mouse twin rotary pencil sharpener desk figurine.', 140, 199,
    30, 'cat-quirky-stationery', 'Quirky Stationery', '/products/stationery/mickey-mouse-sharpeners.jpg',
    '["/products/stationery/mickey-mouse-sharpeners-1.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["stationery","mickey","sharpener"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-3d-chocolate-erasers', '3D Chocolate Erasers (Pack of 4)', '3d-chocolate-erasers-pack-of-4', 'Deliciously realistic chocolate bar miniature novelty erasers in a gift box packaging.', 110, 149,
    26, 'cat-quirky-stationery', 'Quirky Stationery', '/products/stationery/3d-chocolate-erasers-pack-of-4.jpg',
    '["/products/stationery/3d-chocolate-erasers-pack-of-4-1.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["stationery","eraser","chocolate","novelty"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-vine-wrapped-solitaire-ring', 'Vine Wrapped Solitaire Ring', 'vine-wrapped-solitaire-ring', 'Nature-inspired leaf vine band wrapping around a sparkling brilliant cut cubic zirconia solitaire.', 200, 250,
    20, 'cat-rings', 'Rings', '/products/rings/vine-wrapped-solitaire-ring.jpg',
    '["/products/rings/vine-wrapped-solitaire-ring-1.jpg","/products/rings/vine-wrapped-solitaire-ring-2.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["ring","solitaire","vine","anti-tarnish"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-lush-solitaire-ring', 'Lush Solitaire Ring', 'lush-solitaire-ring', 'High-polish pavé band with elevated crown solitaire stone, adjustable sizing.', 200, 250,
    20, 'cat-rings', 'Rings', '',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', FALSE, FALSE,
    FALSE, '["ring","solitaire","silver"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-petal-solitaire-ring', 'Petal solitaire Ring', 'petal-solitaire-ring', 'Floral petal prongs cradling a faceted center diamond crystal.', 200, 250,
    20, 'cat-rings', 'Rings', '/products/rings/petal-solitaire-ring.jpg',
    '["/products/rings/petal-solitaire-ring-1.jpg","/products/rings/petal-solitaire-ring-2.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["ring","petal","solitaire"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-fairytale-tiara-ring', 'Fairytale Tiara Solitaire Ring', 'fairytale-tiara-solitaire-ring', 'Whimsical princess crown tiara design with delicate arches and sparkling accents.', 200, 250,
    20, 'cat-rings', 'Rings', '',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', FALSE, FALSE,
    FALSE, '["ring","tiara","princess","fairytale"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-mini-floral-hairpins-pairs', 'Mini Floral Hairpins Pairs', 'mini-floral-hairpins-pairs', 'Set of two dainty floral pastel bobby hairpins with delicate daisy petals and pearl centers for subtle accents.', 30, 49,
    39, 'cat-hair-accessories', 'Hair Accessories', '/products/hair-accessories/mini-floral-hairpins-pairs.jpg',
    '["/products/hair-accessories/mini-floral-hairpins-pairs-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["hair","hairpins","floral","budget"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-hawaiian-flower-claws-small', 'Hawaiian Flower Claws (Small)', 'hawaiian-flower-claws-small', 'Tropical frangipani / plumeria gradient matte hair claw with sturdy spring grip.', 40, 50,
    20, 'cat-hair-accessories', 'Hair Accessories', '/products/hair-accessories/hawaiian-flower-claws-small.jpg',
    '["/products/hair-accessories/hawaiian-flower-claws-small-1.jpg"]'::jsonb, TRUE, TRUE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["hair","claws","hawaiian","flower","bestseller"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-korean-pearl-hairband', 'Korean Pearl Hairband', 'korean-pearl-hairband', 'Aesthetic headband lined with lustrous faux pearls for elegant hairstyles.', 120, 160,
    25, 'cat-hair-accessories', 'Hair Accessories', '/products/hair-accessories/korean-pearl-hairband.jpg',
    '["/products/hair-accessories/korean-pearl-hairband-1.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["hairband","pearl","korean"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-korean-rosette-bow-pin', 'Korean Rosette Bow Pin', 'korean-rosette-bow-pin', 'Rich satin ribbon oversized bow with rosette center brooch. Available in Black, Pink, White, Rosegold.', 160, 200,
    20, 'cat-hair-accessories', 'Hair Accessories', '/products/hair-accessories/korean-rosette-bow-pin.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["hair","bow","korean","rosette"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-shinchan-mood-swing-keychain', 'Shinchan Mood Swing Toy Keychain', 'shinchan-mood-swing-toy-keychain', 'Fun interactive Shinchan character keychain with bobbling expression swing mechanism.', 120, 180,
    33, 'cat-quirky-keychains', 'Quirky Keychains', '/products/keychains/shinchan-mood-swing-toy-keychain.jpg',
    '["/products/keychains/shinchan-mood-swing-toy-keychain-1.jpg"]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["keychain","shinchan","toy","quirky"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-mirror-evil-eye-keychain', 'Mirror Evil Eye Keychain', 'mirror-evil-eye-keychain', 'Traditional protective blue glass evil eye keychain with reflective mirrored core.', 120, 180,
    33, 'cat-quirky-keychains', 'Quirky Keychains', '/products/keychains/mirror-evil-eye-keychain.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["keychain","evil eye","protection","mirror"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-triple-evil-eye-keychain', 'Triple Evil Eye Keychain', 'triple-evil-eye-keychain', 'Three stacked evil eye glass beads hanging from an ornate braided rope keychain.', 110, 160,
    31, 'cat-quirky-keychains', 'Quirky Keychains', '/products/keychains/triple-evil-eye-keychain.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["keychain","evil eye","amulet"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  ),
(
    'prod-camera-projector-keychain', 'Camera Projector Keychain', 'camera-projector-keychain', 'Mini retro camera keychain that projects adorable pictures when looking into the peephole.', 140, 199,
    30, 'cat-quirky-keychains', 'Quirky Keychains', '/products/keychains/camera-projector-keychain.jpg',
    '[]'::jsonb, TRUE, FALSE, TRUE, NULL,
    'https://charmshub.mart-24.com', TRUE, FALSE,
    FALSE, '["keychain","camera","projector","novelty"]'::jsonb, '2026-03-01T00:00:00.000Z', '2026-09-18T10:45:00.000Z'
  )
ON CONFLICT (id) DO NOTHING;
