-- ==========================================================
-- CHARMS HUB AI — PHASE E2: RAG KNOWLEDGE BASE + PGVECTOR
--
-- Requires: all previous migrations. Safe to re-run.
-- ==========================================================

-- 1. pgvector for semantic retrieval
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Knowledge base: verified business information only.
--    embedding is 768-dimensional (Gemini text-embedding-004 / MRL-768).
CREATE TABLE IF NOT EXISTS public.knowledge_base (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  source TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedding VECTOR(768),
  embedding_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (embedding_status IN ('pending', 'indexed', 'failed')),
  indexed_at TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads active knowledge" ON public.knowledge_base;
CREATE POLICY "Public reads active knowledge"
  ON public.knowledge_base FOR SELECT
  USING (is_active = TRUE OR public.get_user_role(auth.uid()) IN ('shop_owner', 'developer'));

DROP POLICY IF EXISTS "Admins manage knowledge" ON public.knowledge_base;
CREATE POLICY "Admins manage knowledge"
  ON public.knowledge_base FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('shop_owner', 'developer'));

-- 3. Semantic retrieval RPC: cosine similarity with a configurable
--    threshold; only verified active chunks can ever be returned.
CREATE OR REPLACE FUNCTION public.match_knowledge_base(
  p_query_embedding VECTOR(768),
  p_match_threshold FLOAT DEFAULT 0.72,
  p_match_count INT DEFAULT 4
)
RETURNS TABLE (
  id TEXT,
  title TEXT,
  content TEXT,
  category TEXT,
  source TEXT,
  similarity FLOAT
)
LANGUAGE sql
STABLE
SET search_path = public, extensions
AS $$
  SELECT
    kb.id,
    kb.title,
    kb.content,
    kb.category,
    kb.source,
    1 - (kb.embedding <=> p_query_embedding) AS similarity
  FROM public.knowledge_base kb
  WHERE kb.is_active = TRUE
    AND kb.embedding IS NOT NULL
    AND 1 - (kb.embedding <=> p_query_embedding) >= p_match_threshold
  ORDER BY kb.embedding <=> p_query_embedding
  LIMIT GREATEST(LEAST(p_match_count, 10), 1);
$$;

REVOKE ALL ON FUNCTION public.match_knowledge_base(VECTOR(768), FLOAT, INT) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.match_knowledge_base(VECTOR(768), FLOAT, INT) TO authenticated;

-- 4. Product image storage: public read (storefront images), admin write.
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', TRUE)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public read product images" ON storage.objects;
CREATE POLICY "Public read product images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admins write product images" ON storage.objects;
CREATE POLICY "Admins write product images"
  ON storage.objects FOR ALL
  USING (
    bucket_id = 'product-images'
    AND public.get_user_role(auth.uid()) IN ('shop_owner', 'developer')
  )
  WITH CHECK (
    bucket_id = 'product-images'
    AND public.get_user_role(auth.uid()) IN ('shop_owner', 'developer')
  );

-- 5. Seed verified business knowledge (embeddings generated by the
--    embed-knowledge Edge Function; rows start as 'pending').
INSERT INTO public.knowledge_base (id, title, content, category, source, metadata)
VALUES
  ('kb-free-shipping', 'Free Shipping Threshold',
   'Charms Hub offers free shipping on all orders above Rs. 499. For orders below Rs. 499, a flat courier shipping charge of Rs. 50 applies at checkout.',
   'shipping', 'Charms Hub website top banner and checkout',
   '{"type": "business_policy", "min_order_value": 499, "flat_fee": 50}'),
  ('kb-delivery-duration', 'Delivery Timelines',
   'Orders are dispatched within 24-48 business hours. Standard delivery across India usually takes 4 to 7 business days depending on your pin code location. Courier tracking information is not available yet.',
   'shipping', 'Charms Hub shipping policy',
   '{"timeline": "4-7 business days"}'),
  ('kb-ordering-process', 'How to Place an Order',
   'To place an order on Charms Hub: 1. Browse products and add your desired items to the cart. 2. Sign in and complete checkout with your full shipping address. 3. Choose UPI or Cash on Delivery and confirm the order. An invoice is generated automatically and available under Account -> My Orders.',
   'ordering', 'Charms Hub checkout workflow',
   '{"type": "workflow"}'),
  ('kb-payment-upi', 'UPI Payments',
   'Charms Hub accepts UPI payments. After paying to the merchant UPI ID shown at checkout, enter your UPI transaction or reference ID with the order. UPI payments are marked as Pending Verification until the team manually confirms receipt - the store never claims automatic payment confirmation.',
   'payments', 'Charms Hub checkout payment section',
   '{"payment_status": "Pending Verification"}'),
  ('kb-payment-cod', 'Cash on Delivery',
   'Cash on Delivery is available across India. Pay the courier in cash when the package arrives. No advance payment is required and no refund process applies to COD orders.',
   'payments', 'Charms Hub checkout payment section',
   '{"payment_status": "Cash on Delivery"}'),
  ('kb-cancellation-policy', 'Order Cancellation Policy',
   'Customers can cancel an order from Account -> My Orders while it is Pending, Confirmed, or Processing. Orders that are already Shipped or Delivered cannot be cancelled. Cancelled Cash on Delivery orders require no refund. Cancelled prepaid (UPI) orders are marked Refund Required and are reviewed manually by the team.',
   'cancellation', 'Charms Hub cancellation policy',
   '{"cancellable_statuses": ["Pending", "Confirmed", "Processing"]}'),
  ('kb-return-policy', 'Return and Unboxing Video Requirement',
   'For any damaged, missing, or incorrect items, a 360-degree unboxing video from start to finish without cuts or pauses is strictly required within 24 hours of package delivery for replacement or claims.',
   'returns', 'Charms Hub Return Policy',
   '{"type": "policy"}'),
  ('kb-packaging-video', 'Order Packaging Video on Instagram Story',
   'Charms Hub records and uploads order packaging videos for customers on the official Instagram Story so you can watch your package being prepared. Add your Instagram handle at checkout to get tagged.',
   'business_information', 'Charms Hub announcement banner',
   '{"platform": "Instagram"}'),
  ('kb-mystery-scoop-types', 'Mystery Scoop Options and Pricing',
   'Charms Hub offers 4 verified Mystery Scoop tiers: 1. Pookia Mystery Scoop at Rs. 399. 2. Mini Mystery Scoop at Rs. 399. 3. Anti-tarnish Jewelry Mystery Scoop at Rs. 799. 4. Luxury Mystery Scoop at Rs. 1,200. All scoops are curated surprises. Current prices are always shown on the product pages.',
   'product_guidance', 'Charms Hub Mystery Scoop section',
   '{"type": "product_category"}'),
  ('kb-anti-tarnish-care', 'Anti-tarnish Jewelry Care Instructions',
   'Anti-tarnish jewelry is crafted from quality stainless steel with premium plating. To prolong its lifespan, keep it dry, avoid direct contact with perfumes, deodorants, or swimming pools, and store it in an airtight zip pouch or jewelry organizer.',
   'product_guidance', 'Charms Hub jewelry care guide',
   '{"type": "care_instructions"}'),
  ('kb-contact-support', 'Customer Support and Contact',
   'You can reach Charms Hub customer support via the WhatsApp button on the website, or by messaging the team after placing an order. Support is available for order status, cancellations, and product questions.',
   'customer_support', 'Charms Hub footer and support',
   '{"type": "contact"}'),
  ('kb-product-availability', 'Product Availability and Pricing Accuracy',
   'Product availability, prices, discounts, and stock status shown by this assistant come directly from the live Charms Hub database. If a product is out of stock or archived, it cannot be purchased until the shop owner restocks it.',
   'faq', 'Charms Hub catalog system',
   '{"type": "faq"}')
ON CONFLICT (id) DO NOTHING;
